title: Michael Miller # your name (or website title) here
logo: "/images/Mike Miller.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Husband, Father, Podcaster, Learning Data Analysis
  <br><br>
  I created this humble site to provide a place to store different projects. I started to learn SQL and Python in 2021. 
  Since that time, My SQL knowledge has grown to meet the needs for developing reports and dashboards. Each section reflects the work
  I created either for work or personal learning. 
  <br><br>
  <a href="https://www.linkedin.com/in/mikemiller117/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-QSZL9GBWDF # your Google Analytics tracking ID here
